### ISSUE TITLE
404 page is json, not html

### ISSUE THREAD

**Issue by amandasaurus** [developmentseed/osm-teams#116]
The 404 page returns raw json, as opposed to a html page:

http https://dev.mapping.team/teams/60
HTTP/1.1 404 Not Found
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 74
Content-Type: application/json; charset=utf-8
Date: Fri, 06 Sep 2019 07:53:50 GMT
ETag: W/"4a-jEQnxGWEu7sUkCWsROf0+5s08hU"
Server: nginx/1.14.0 (Ubuntu)
Set-Cookie: osm-teams.sid=XXX
Vary: Accept-Encoding
X-Powered-By: Express

{
    "error": "Not Found",
    "message": "Could not find resource",
    "statusCode": 404
}

**Comment by vgeorge** [comment]
This was fixed on `develop` branch.
