### ISSUE TITLE
Role system & middleware

### ISSUE THREAD

**Issue by kamicut** [developmentseed/osm-teams#12]
This is a meta ticket for a role system for OSM teams. The middleware should be able to make a decision for each request to either allow or deny a request.

Basic roles for teams:
- team moderator
- user

A moderator is the first person that created a team. A moderator has special privileges that a user does not have:
- assign new moderators for their team
- add new members to the team
- remove members from the team
- change the settings of a team

There is an additional role: OSM teams admin. The admin does not have privileges over a team (unless they are a moderator of a team), but they have control over the OSM Teams API settings, such as token creation and app creation. Since the role of admin is more nebulous IMO it's lower priority to implement.

To complete the role system we should:
- [ ] Create a `role x permissions` table
- [ ] Implement the middleware
- [ ] Create tests for each role x permission

Any other thoughts @sethvincent @alyssadelaine ?

**Comment by alyssadelaine** [comment]
In our MVP version of the hierarchy, admins designate moderators, so I think it's still important for this to implement the `admin` roles and permissions

**Comment by kamicut** [comment]
In our internal discussion I think that is correct for downstream apps like Scoreboard, but for the osm-teams API we can keep the model more permissive and narrow-scoped with just moderators and users.

**Comment by sethvincent** [comment]
Great I'll get started on this.

`Create a role x permissions table`

To what extent does this need to model the different types of permissions a role might have? It seems like that could get complicated.

It looks like there's already a moderators table that relates users to teams https://github.com/developmentseed/osm-teams/blob/master/db/migrations/20181024145945_create_tables.js#L12

If we use that moderators table the todos look like:

- [ ] make the creator of a team the moderator when a team is created
- [ ] methods for adding/removing moderators of a team
- [ ] authorization middleware
- [ ] tests

**Comment by kamicut** [comment]
@sethvincent sorry for the confusion by table I meant a spreadsheet and didn't think of database tables.

**Comment by sethvincent** [comment]
@kamicut should this have been closed by #31?

**Comment by kamicut** [comment]
Yes I think we can close this and move to other tickets
