### ISSUE TITLE
Question: osm-teams and microcosm

### ISSUE THREAD

**Issue by RobJN** [developmentseed/osm-teams#125]
Hi,

A question more than an issue. At this year's State of the Map series of events we saw presentations on this (at Heidelberg) and Microcosm (at Minneapolis, SotM US). At face value both seem to have similar features. Can I kindly ask what consideration has been made to coordinating together on a single solution? The OSM community is already quite fractured (hence these teams/groups ideas are so great) and it would be confusing to have to join groups on two different systems.

Microcosm:
https://github.com/openstreetmap/openstreetmap-website/pull/2390

P.S. It appears that there is support for adding this functionality into openstreetmap.org. Indeed Brian comments in the SotM US talk that he was advised to integrate the functionality into the site after floating the initial idea. Other recent comments by the key developers have indicated support for API improvements.

**Comment by kamicut** [comment]
Hey @RobJN, we've talked with Brian and we definitely want both projects to integrate. We launched OSM Teams as a way to come up with the minimum feature API for integrating the ecosystem apps like OSMCha and Tasking Manager that need groups right now. If the OSM API starts providing groups, we can then find a path forward for this API.

**Comment by RobJN** [comment]
> we've talked with Brian and we definitely want both projects to integrate.

That's great. And I fully get the point about getting something up an running for an immediate need. Any ideas how we best ensure that the projects integrate?

**Comment by LanesGood** [comment]
Based on the evolution of the microcosms/communities project and the conversations in https://github.com/openstreetmap/openstreetmap-website/pull/3717 and elsewhere, it seems more clear that the two types of "osm user groups" serve quite different purposes; associating a group of user id's (OSM Teams), vs. organizing a group for mapping activities within the OSM website (OSM Communities). 

We're exploring OSM Teams integration within other OSM apps; see evolution in #289

**Comment by RobJN** [comment]
I'm not sure I agree that the OSM Communities is solely about "group[s] for mapping activities", in fact I hope it is not that narrow even though that appears to be the developers main use case at the moment. Having said that, I can fully understand why you'd want to do something outside of the OSM.org website. It's a shame as I feel that we suffer from a fractured setup spreading things all over the place, but often it's the easiest route forward :-(
