### ISSUE TITLE
Team Members list view is styled for navigation but does not link to anywhere

### ISSUE THREAD

**Issue by guidorice** [developmentseed/osm-teams#126]
The team members table (I added yellow box at bottom of screenshot) is styled with a pointer cursor on hover, so I expect a navigation event to happen when I click on it. Should it link to https://www.openstreetmap.org/user/USERNAME ?

<img width="1858" alt="Screen Shot 2020-01-22 at 11 54 28 AM" src="https://user-images.githubusercontent.com/766758/72924531-5437c900-3d0e-11ea-8916-359a30cd9008.png">

**Comment by LanesGood** [comment]
Clicking a team member now opens the "user profile." Closing
