### ISSUE TITLE
(api-only) Team moderators can assign other users as moderators

### ISSUE THREAD

**Issue by LanesGood** [developmentseed/osm-teams#127]
Team moderators (currently, the user who created the team) should be able to designate other users as team moderators. 

More information is discussed in the initial issue #12 and related PR's linked there.

Additional questions to answer:
- Once a team moderator has assigned another user as the moderator, can they remove their own moderator distinction? Can they remove themself from a team?
- How are users notified that they have been designated as team moderators?

/cc @kamicut

**Comment by guidorice** [comment]
> How are users notified that they have been designated as team moderators?

@LanesGood  I agree there should be UI affordances so a user can discover who are the moderator(s) of a team, and what teams they are moderator(s) of. 

But a *notification* mechanism is another level of functionality: it could be in-app notifications, desktop notifications, email, sms, web hooks, zapier, etc. I propose for initial implementation we should not do notifications, and instead rely on outside-the-app communications between team members.
We should discuss how notifications can be implemented consistently across the app and also to interoperate with client apps, e.g Scoreboard.

**Comment by LanesGood** [comment]
@guidorice great point - notifications are indeed a separate issue. I'll open a new ticket.

**Comment by guidorice** [comment]
Initially and today I am focusing on making changes to the API so the functionality is there. 
Enhancements to the UI can be implemented after that.
