### ISSUE TITLE
Make New Team: defaults to "no location specified"

### ISSUE THREAD

**Issue by guidorice** [developmentseed/osm-teams#129]
To reproduce the "no location specified" state, go to the Make New Team form, and enter in only the team Name, then hit Submit.

This seems like a bug because the Location map defaults to a point in Washington DC. It's possible the user will want to use Washington DC, see it appears to be in that location,  and so does not interact with the map. Apparently interacting with the map by search, zoom or pan causes the app state to be updated with an actual location.

If "No location" teams are to be supported, consider having an explicit toggle for that in the team editing form.

**Comment by LanesGood** [comment]
Can confirm that this bug exists, and is still present in the latest version of the app.
