### ISSUE TITLE
Navigation problem with Explore Teams (component's content not visible)

### ISSUE THREAD

**Issue by guidorice** [developmentseed/osm-teams#131]
To reproduce this bug

1.  Scroll to the bottom of the Explore Teams table view:
<img width="1557" alt="Screen Shot 2020-01-22 at 2 45 57 PM" src="https://user-images.githubusercontent.com/766758/72937523-8a814280-3d26-11ea-8cd2-5232bd11bb30.png">

2. Click on the last team, and you will see a blank viewport. The content is there but you have to scroll up to see it. There are workarounds that could be done: either by setting the Element.scrollTop, or ideally, by replacing the whole container element when the props change (edit: maybe not- depends on implementation. There is probably an idiomatic way of handling this situation in React)

<img width="1557" alt="Screen Shot 2020-01-22 at 2 51 14 PM" src="https://user-images.githubusercontent.com/766758/72937602-ab499800-3d26-11ea-9de4-ff7e2e377176.png">

Relates to #130

**Comment by LanesGood** [comment]
I no longer see this bug - I believe it was fixed in https://github.com/developmentseed/osm-teams/pull/309
