### ISSUE TITLE
Layout issue on Team detail page

### ISSUE THREAD

**Issue by guidorice** [developmentseed/osm-teams#132]
There is a lot of vertical padding on the Team detail page and so it appears to have a different layout than most of the other pages on the site. This could be as simple as a flexbox css setting, but we can investigate:

<img width="1818" alt="Screen Shot 2020-01-22 at 4 15 50 PM" src="https://user-images.githubusercontent.com/766758/72943271-e4880500-3d32-11ea-96f5-6bac08fc07d7.png">

**Comment by LanesGood** [comment]
I'm not seeing this. I thought it might be a monitor size issue, but have tested on my 21" HD monitor and no change.

13" Laptop on Chrome:
![screencapture-localhost-8989-teams-49-2020-01-23-11_49_11](https://user-images.githubusercontent.com/12634024/73005151-772db000-3dd6-11ea-892e-f94fad87b34c.png)

21" Monitor on Chrome
![screencapture-dev-mapping-team-teams-49-2020-01-23-17_27_51](https://user-images.githubusercontent.com/12634024/73029581-ca6b2700-3e05-11ea-8b0e-0cf0781fb1ea.png)

13" Laptop on Firefox:
![Screenshot_2020-01-23 OSM Teams](https://user-images.githubusercontent.com/12634024/73005154-78f77380-3dd6-11ea-8a57-5f58a85ec558.png)

21" Monitor on Firefox
![Screenshot_2020-01-23 OSM Teams(1)](https://user-images.githubusercontent.com/12634024/73029609-dce56080-3e05-11ea-8f31-e9b3bd4346b0.png)

**Comment by guidorice** [comment]
@LanesGood OK so I think the discrepancy is because of this: OS X has a virtual pixel system (aka Retina) where even if your monitor is HD or 4K or whatever, it's virtual pixel count is not always the max  the monitor is capable of. I suggest verifying your Display Settings in system preferences. 

Or, even better, use Chrome's developer tools to "toggle device toolbar", and enter into a custom resolution: 


Here it is using the iPad Pro preset:


<img width="582" alt="Screen Shot 2020-01-24 at 9 07 12 AM" src="https://user-images.githubusercontent.com/766758/73083736-f380cb80-3e88-11ea-8227-085be4ab6439.png">

Here is the page rendered in chrome at 4K full resolution (I entered the pixel values as a custom setting)

<img width="1824" alt="Screen Shot 2020-01-24 at 9 04 25 AM" src="https://user-images.githubusercontent.com/766758/73083597-b4eb1100-3e88-11ea-8039-90254cc4f7f6.png">

**Comment by LanesGood** [comment]
Addressed in #309
