### ISSUE TITLE
Hydra image is using a older release candidate (RC)

### ISSUE THREAD

**Issue by guidorice** [developmentseed/osm-teams#134]
Consider changing the image in docker-compose.yml and docker-compose.dev.yml from oryd/hydra:v1.0.0-rc.11 to one of

oryd/hydra:v1
oryd/hydra:latest

source https://hub.docker.com/r/oryd/hydra/tags

**Comment by guidorice** [comment]
@kamicut there is no way to predict if we'll encounter problems but here are some observations:

There where 5 RC's after RC11, suggesting there must have been some bugs in RC11.

The latest in the v1 series is v1.2.3. So osm-teams is pretty far behind. https://github.com/ory/hydra/releases

Anecdotally `oryd/hydra:v1` works fine and all our unit+integration tests run OK in my PR #141 .

We should trust semantic versioning (we are still using the same major version v1).  I would be concerned about continuing to stay with an outdated old Release Candidate.

**Comment by kamicut** [comment]
One thing that changes that I had to do locally is to migrate the database (new migrations have to be applied) using the instructions in the `README`
