### ISSUE TITLE
Docs: docker.env is needed for docker-compose build

### ISSUE THREAD

**Issue by batpad** [developmentseed/osm-teams#14]
Minor documentation issue: the `docker-compose build` command seems to require `docker.env` to be present, but creation of `docker.env` is only mentioned in subsequent steps.

cc @kamicut

**Comment by batpad** [comment]
This was what I got when trying to run `docker-compose build` without a `docker.env` present:

```
$ docker-compose build
ERROR: Couldn't find env file: /Users/admin/seed/osm-teams/docker.env
```

**Comment by kamicut** [comment]
This is mentioned here @batpad? https://github.com/developmentseed/osm-teams#setting-up-hydra (in step 2)

**Comment by sethvincent** [comment]
I hit this when I was setting things up as well. We may want to reorder some of the instructions.

**Comment by batpad** [comment]
> I hit this when I was setting things up as well. We may want to reorder some of the instructions.

Sorry, yes - this is what I meant - this is mentioned, just in the wrong order - the setting up of `docker.env` should come before the `docker-compose build` step.

**Comment by kamicut** [comment]
ah ok, thanks!

**Comment by kamicut** [comment]
I wonder if this is because next.config.js has `require('dotenv').config()`. I don't think we need it in a docker environment so I will investigate removing it.
