### ISSUE TITLE
serialize-javascript vulnerability found in yarn.lock 

### ISSUE THREAD

**Issue by guidorice** [developmentseed/osm-teams#143]
https://github.com/developmentseed/osm-teams/network/alert/yarn.lock/serialize-javascript/open

This dependency appears to be coming from 

- nextjs
- terser-webpack-plugin

The [advisory](https://github.com/developmentseed/osm-teams/network/alert/yarn.lock/serialize-javascript/open) says nodejs is not effected. So we can ignore the webpack plugin. However I do think we need to address the nextjs dependency. 

- Does an update of nextjs 8.x fix this version?
- Can we verify that nextjs's usage of `serialize-javascript` only occurs in nodejs environment and not in browser environment? then the vulnerability could be dismissed as an acceptable risk for the project.
- Prioritize upgrading to nextjs 9?

**Comment by vgeorge** [comment]
This will be addressed in https://github.com/developmentseed/osm-teams/issues/258.
