### ISSUE TITLE
Review development environment

### ISSUE THREAD

**Issue by kamicut** [developmentseed/osm-teams#151]
When moving to the new development docker-compose, we kept instructions for installing node_modules and migrating the database outside of docker. If we want to do all development through docker & hot-module reloading, then we don't need to do a separate install & migrate step outside of docker.

**Comment by guidorice** [comment]
Related to this

https://github.com/developmentseed/osm-teams/blob/master/docker-compose.dev.yml#L33

The node_modules folder is mounted as a volume.

**Comment by vgeorge** [comment]
The development environment is working well on v2 (`develop` branch).
