### ISSUE TITLE
Error: Undefined binding(s) detected when compiling SELECT

### ISSUE THREAD

**Issue by guidorice** [developmentseed/osm-teams#160]
This seems to not really effect functionality, but when the osm-teams app is started, and the homepage is loaded, but user has not signed in yet, there error that I am seeing in the docker log:

This error seems to get quieted down after user signs in. It seems to have something to do with the pre-authenticated state of the app? Or maybe it is a race condition where one of the docker containers is still starting up?

```
teams_1  | error checking permission Error: Undefined binding(s) detected when compiling SELECT. Undefined column(s): [id] query: select * from "users" where "id" = ?
teams_1  |     at QueryCompiler_PG.toSQL (/usr/src/app/node_modules/knex/lib/query/compiler.js:101:13)
teams_1  |     at Builder.toSQL (/usr/src/app/node_modules/knex/lib/query/builder.js:77:44)
teams_1  |     at /usr/src/app/node_modules/knex/lib/runner.js:30:36
teams_1  |     at client.acquireConnection.catch.then (/usr/src/app/node_modules/knex/lib/runner.js:253:24)
```

Relates to #156

**Comment by vgeorge** [comment]
Unable to replicate this, it was probably gone after the authentication refactor.

cc @kamicut @batpad
