### ISSUE TITLE
Double scrollbars

### ISSUE THREAD

**Issue by LanesGood** [developmentseed/osm-teams#165]
UI error: the overflow on the inner teams panel results in a double scrollbar:

<img width="925" alt="Screen Shot 2020-04-02 at 9 37 46 AM" src="https://user-images.githubusercontent.com/12634024/78256553-b0655900-74c6-11ea-830d-020f1745c50b.png">

**Comment by guidorice** [comment]
@LanesGood this may be the same issue, or related to #130.
