### ISSUE TITLE
assign moderator in the UI

### ISSUE THREAD

**Issue by kamicut** [developmentseed/osm-teams#167]
Right now the UI doesn't include "assign moderator" anywhere. We should include it as part of the actions in the teams table.

**Comment by LanesGood** [comment]
We now have the ability to "Promote to Moderator" in a teams table.
![image](https://user-images.githubusercontent.com/12634024/211953238-8717a5e7-f0f6-4cab-b3a1-1973f3291ef0.png)

Future design iterations will streamline this workflow. Closing, implemented as described in top issue.
