### ISSUE TITLE
Swagger api validator error "attribute components.schemas.Client.items is missing"

### ISSUE THREAD

**Issue by guidorice** [developmentseed/osm-teams#171]
In #168 we added  a `swagger-cli validate` step to the package.json scripts. In addition, a badge was added to the Readme. Surprisingly, the two different validators have different opinions:

http://validator.swagger.io/validator/debug?url=https://raw.githubusercontent.com/developmentseed/osm-teams/master/docs/api.yml

> "attribute components.schemas.Client.items is missing"

**Comment by vgeorge** [comment]
No validation errors are occuring now.
