### ISSUE TITLE
Productionize osm-teams

### ISSUE THREAD

**Issue by kamicut** [developmentseed/osm-teams#205]
- [x] Transition OSM Teams to automated CI/CD
- [x] Patch security issues
- [ ] Load testing
- [x] QA testing
- [x] Remove Beta banner
- [x] Set up staging environment in Vercel

**Comment by vgeorge** [comment]
Testing and deployment automated pipelines are set and deploying to Vercel:

- Prod: https://mapping.team
- Dev: https://dev.mapping.team

We implemented username caching, which fixed an important bottleneck for the app. It doesn't look like we need load testing now, let's open a separate ticket if we need it.

cc @batpad @kamicut
