### ISSUE TITLE
Automate deployment

### ISSUE THREAD

**Issue by kamicut** [developmentseed/osm-teams#206]
Currently osm-teams is dockerized but not deployed automatically on code pushes:
- Create a staging deployment
- Connect CI pipeline to deploy push

This could be done in 2 ways: 
1. osm-teams application is deployed to a non-docker platform such as `vercel`, while the hydra app is deployed as docker on digitalocean or AWS
2. osm-teams application is dockerized and both containers run on the same platform.

**Comment by vgeorge** [comment]
This is done. Branch `main` is deploying to https://mapping.team/ and the `develop` branch is deploying to https://dev.mapping.team/.
