### ISSUE TITLE
No close button after 'create' button on profile

### ISSUE THREAD

**Issue by jenningsanderson** [developmentseed/osm-teams#237]
After pressing "Create" in the upper right corner, this box pops up with no way to get back: 

![image](https://user-images.githubusercontent.com/1637425/151054797-e065b6f8-142a-4710-9bb6-a674ef4c58f4.png)

**Comment by kamicut** [comment]
@LanesGood I don't like that this is a modal. What do you think is the best UI here?

**Comment by LanesGood** [comment]
@kamicut one option could be a dropdown with the different options available. Alternatively, we could display both buttons on the profile page, either adjacent to eachother or associated with the respective tables.

Are these tables paginated? We'll want to explore what the proper UI should be for many orgs and teams on a profile page.

**Comment by LanesGood** [comment]
This button was removed, as was the modal; we do need a new "Create Org" option, and this is being included in the redesign.
