### ISSUE TITLE
Cannot create a new team

### ISSUE THREAD

**Issue by jenningsanderson** [developmentseed/osm-teams#262]
I get this error when trying to create a new team: 

<img width="532" alt="image" src="https://user-images.githubusercontent.com/1637425/162003286-d0dd915b-001b-4ad8-abbf-0a2bdcffd54b.png">

**Comment by jenningsanderson** [comment]
Logging in/out does solve this.

**Comment by vgeorge** [comment]
@jenningsanderson I believe this will be corrected once we fix https://github.com/developmentseed/osm-teams/issues/140, which is part of the release milestone.
