### ISSUE TITLE
Team moderator access to attributes

### ISSUE THREAD

**Issue by jenningsanderson** [developmentseed/osm-teams#286]
Current Behavior: 
Team members with `moderator` role are able to see `EDIT` button on Team page, but get "Team not found" error when attempting to edit team attributes.

Desired Behavior:
Team moderators _should_ have edit rights over team attributes.

**Comment by LanesGood** [comment]
Not reproducible on local development, only exists in production. We will need access to production logs.

**Comment by kamicut** [comment]
Fixed and deployed to https://mapping.team/ cc @batpad @vgeorge
Please confirm it works @jenningsanderson
