### ISSUE TITLE
Load from cache when OSM user API is under-performing

### ISSUE THREAD

**Issue by jenningsanderson** [developmentseed/osm-teams#288]
As teams grow, the dependency on the OSM User API will increase.

I noticed today that for whatever reason, the OSM User API is extraordinarily slow and dropping connections; as a result, team pages on mapping.team take 10-15 seconds to load (just a blank white page that suddenly appears).

Some type of spinner / status for loading a page is one solution, or better, a fallback to stored data after 1 second would be a huge improvement.

**Comment by jenningsanderson** [comment]
Update: Hanging and returning `Error: could not retrieve organization`

**Comment by batpad** [comment]
We are now caching OSM usernames and all display of OSM usernames will be coming from our database, so we should not have this issue any more!
