### ISSUE TITLE
Team Detail: Add external links in a row

### ISSUE THREAD

**Issue by batpad** [developmentseed/osm-teams#292]
External links to add:

 OSM User Profile? OsmCha? HDYC? Link to message a user on OSM?

**Comment by LanesGood** [comment]
Need to build links on OSM User IDs

**Comment by batpad** [comment]
Based on chat with @vgeorge : @vgeorge can implement adding these external links and then probably hand back to you for styling @LanesGood

**Comment by batpad** [comment]
@vgeorge do you think you would be able to look at this after the work on tables? Happy to discuss - hopefully this is a fairly low lift and can be handed off to Lane for styling?

**Comment by vgeorge** [comment]
@batpad this looks straightforward to implement. Some questions:

- Are we implementing this only on the team view page? Or should we also add it to staff/members tables on the organization page?
- On the user profile page at the OSM website there is a link to send a message, do we really need to add the link to the profile and send a message in OSM Teams table?
- How can I build an OSMCha URL for a user? cc @willemarcel 
- Is there any other service other than OSM profile, HDYC, and OSMCha we want to link?

cc @LanesGood

**Comment by willemarcel** [comment]
> * How can I build an OSMCha URL for a user? cc @willemarcel

You can build it with the username https://osmcha.org/?filters={"users":[{"label":"wille","value":"wille"}]} or with the uid https://osmcha.org/?filters={"uids":[{"label":"360183","value":"360183"}]}

**Comment by batpad** [comment]
> On the user profile page at the OSM website there is a link to send a message, do we really need to add the link to the profile and send a message in OSM Teams table?

I think it makes sense to just link to the OSM profile page, in that case.

> Are we implementing this only on the team view page? Or should we also add it to staff/members tables on the organization page?

I think the team view page is the more important one, but if its not too much extra work, I think it makes sense to have it in both places. @jenningsanderson does that sound right?

**Comment by LanesGood** [comment]
Closed via #378
