### ISSUE TITLE
Badges: Team moderators & Org. managers/owners should be able to assign badges from the Teams List

### ISSUE THREAD

**Issue by batpad** [developmentseed/osm-teams#296]
- [x] #387
- [x] #388

**Comment by LanesGood** [comment]
Proposed team page flow:
- go to individual member row on team page members table
- Click "Actions"
- Click "Assign badge"
- fetch organization id, fetch badges

**Comment by LanesGood** [comment]
- Remove hover state on user in teams table row
- Move profile modal trigger to the user name column
- Add "Actions" column with button
- Actions column button click triggers Actions modal popup, containing:
    - Promote/Demote
    - Remove member
    - Assign badge

**Comment by LanesGood** [comment]
Closed by #415
