### ISSUE TITLE
Team attributes not saving on edit

### ISSUE THREAD

**Issue by jenningsanderson** [developmentseed/osm-teams#308]
As a team moderator of team #52, when I add a new hashtag to the team details, the change does not persist.

**Comment by kamicut** [comment]
oh no what’s this

**Comment by vgeorge** [comment]
I was able to replicate the issue by adding a hashtag that already belongs to another team. 

The correct behavior should be to display a validation error when a hashtag is already present.

cc @jenningsanderson @LanesGood @kamicut

**Comment by jenningsanderson** [comment]
Interesting; I think that multiple teams should be able to share hashtags?

**Comment by batpad** [comment]
I believe this is fixed. Please re-open if necessary.
