### ISSUE TITLE
Forbid last team moderator from downgrading own moderator status

### ISSUE THREAD

**Issue by LanesGood** [developmentseed/osm-teams#313]
If only a single moderator exists on a team, they should not be able to downgrade/remove their moderator status. Instead, the "downgrade/remove" action should display the hint "You must first promote another user as moderator before removing your own moderator status."

**Comment by LanesGood** [comment]
Same as #314; It seems this may already exist on the API. @kamicut or @vgeorge can you confirm?

If so, we only need to ensure that the "downgrade moderator" option is not available/disabled for the last/only team moderator for a team by rendering this conditionally.

**Comment by vgeorge** [comment]
This exists in the API, as pointed out [here](https://github.com/developmentseed/osm-teams/issues/314#issuecomment-1378661403). This is a UI issue.

**Comment by LanesGood** [comment]
Closed by https://github.com/developmentseed/osm-teams/pull/415
