### ISSUE TITLE
Forbid only team moderator from removing self from team

### ISSUE THREAD

**Issue by LanesGood** [developmentseed/osm-teams#314]
If a team has only a single moderator, that moderator should not be able to remove themself from a team. Instead, they should see an error message stating something along the lines of: "You must first promote another user to moderator before removing yourself"

**Comment by LanesGood** [comment]
It seems this may already exist on the API. @kamicut or @vgeorge can you confirm?

If so, we only need to ensure that the "remove moderator" option is not available/disabled for the last/only team moderator for a team by rendering this conditionally.

**Comment by vgeorge** [comment]
@LanesGood I confirm the API doesn't allow the last moderator to be removed (see [here](https://github.com/developmentseed/osm-teams/blob/de95cd323a82d4a36c40039dbc1ddc303b779e9f/src/models/team.js#L476-L493)), this is a front-end issue.

**Comment by LanesGood** [comment]
Closed by https://github.com/developmentseed/osm-teams/pull/415
