### ISSUE TITLE
Switch styling library

### ISSUE THREAD

**Issue by LanesGood** [developmentseed/osm-teams#315]
Consider switching from Styled-JSX to Styled Components or similar. Styled-JSX does not support nesting, and lacks many of the features we've become used to with other, better supported css-in-js libraries available.

**Comment by LanesGood** [comment]
@vgeorge you mentioned that Styled Components would not be available in the project with the current Next.js setup. I'm not sure I understand what the issue is - I see lots of documentation of NextJS working with Styled Components.

**Comment by vgeorge** [comment]
@LanesGood I read somewhere Styled Components needed some special config to work with server-side rendering, but I probably read wrong. I agree we should try using it.

**Comment by LanesGood** [comment]
Noting we're also considering switching to Chakra UI for future styling and redesign

**Comment by LanesGood** [comment]
Implemented in #411, closing
