### ISSUE TITLE
Add Button Linking to Profile 

### ISSUE THREAD

**Issue by Notoncebut2x** [developmentseed/osm-teams#350]
Currently the `EDIT YOUR PROFILE` button is only accessed when you are on a specific team you are part of.  It would be nice to view and be able to edit your profile on the Profile page of OSM Teams.

**Comment by jenningsanderson** [comment]
Building on this (and I know this has been discussed as part of the UI facelift) — but it would be great to have org-level attributes show up on the profile page as well, especially in cases where mappers are only part of 1 organization.

**Comment by LanesGood** [comment]
Implemented, closing. (Edit profile button present on teams for editing the individual team profiles; a single aggregate profile page for capturing all team & org attributes in one place will be ticketed separately for later exploration)
