### ISSUE TITLE
Can't edit organization attributes?

### ISSUE THREAD

**Issue by jenningsanderson** [developmentseed/osm-teams#410]
There is no option to edit these attributes on the organization edit page? 

![image](https://user-images.githubusercontent.com/1637425/221992455-e49d7603-552c-4f42-a306-2b6a38e14ca8.png)

**Comment by LanesGood** [comment]
After digging into this, I found that the render method for the "actions" column in the attributes tables was not being passed to the Table component. Fixed in https://github.com/developmentseed/osm-teams/pull/411/commits/ba9874eceaf7a760bfca66137cce07c6836d4add
