### ISSUE TITLE
Team editor

### ISSUE THREAD

**Issue by kamicut** [developmentseed/osm-teams#45]
We need to create a mechanism to edit the team:

1. Edit the bio
2 Add and remove users 

cc @LanesGood for suggestions on how this should look

**Comment by LanesGood** [comment]
@kamicut The UI for team edits, adding users, and filtering teams is so far proposed to be housed in the sidebar.

![Team Page - Admin Edit](https://user-images.githubusercontent.com/12634024/62159118-fbe3b980-b2de-11e9-88c1-c295c1d98ca9.png)
![Team Page - Admin Add Members](https://user-images.githubusercontent.com/12634024/62159117-fbe3b980-b2de-11e9-8972-f76ca054f9ce.png)


This raises the following questions:

- Who can edit team bios and add/remove users: all team moderators?
- Can users be added via a comma-separated list, or is this only a one-by-one process?
- Should the "Edit Team" screen/interface be distinct from the "Create Team" interface, or should these follow the same process and views?

**Comment by LanesGood** [comment]
The Edit team page has been implemented, and allows editing of the bio and adding members. Closing
