### ISSUE TITLE
global navigation

### ISSUE THREAD

**Issue by sethvincent** [developmentseed/osm-teams#48]
As part of #26 we should add some basic global navigation. As we add pages it's getting more difficult to navigate.

**Comment by kamicut** [comment]
@LanesGood how do you envision this? Should it be a navbar?

**Comment by sethvincent** [comment]
the left navbar as shown in #51 looks good.

**Comment by LanesGood** [comment]
@kamicut @sethvincent yes, I think a side navbar is the right pattern to make this approach a more modular dashboard design. We should determine here or in the main UI thread what the main navigation items are, and the actions of each. The main actions will be displayed in the expanded sidebar. So far I've captured:

- Explore Teams
     - Filter Teams
     - Create Team
- My Teams
     - Edit Team
- For Developers
     - Add App
- Home/About
