### ISSUE TITLE
Error/warning/info toast component

### ISSUE THREAD

**Issue by sethvincent** [developmentseed/osm-teams#49]
We need a way to notify users of the status of requests in response to clicking buttons and other actions.

We're looking at using: https://jossmac.github.io/react-toast-notifications/

**Comment by sethvincent** [comment]
This issue previously kinda confused the idea of a toast ui element with 404 and other error pages. Moved error pages to this issue: https://github.com/developmentseed/osm-teams/issues/95

**Comment by vgeorge** [comment]
This should be introduced in #256.
