### ISSUE TITLE
handle osm api request errors

### ISSUE THREAD

**Issue by sethvincent** [developmentseed/osm-teams#56]
Sometimes this request can send back a 404 if one of the user ids doesn't exist (I assume because people can delete their osm account?). 

https://github.com/developmentseed/osm-teams/blob/23f91565d8004b9d36e0dc7586251389f51fc264/app/lib/team.js#L25

Let's add a try/catch there and return early in case of error. Then the ui can provide a message about that user not being available.

**Comment by kamicut** [comment]
I don't think this should happen on `resolveMemberNames`, if you are already a member, then you have an account and thus a displayName. There is no mechanism to delete your own account on OSM, but I'm wondering what happens to malicious users that get deleted by the admins.

**Comment by sethvincent** [comment]
If the request to the osm api fails the ui doesn't get a response back. It just waits until the request times out.
