### ISSUE TITLE
Going to a team page as unauthenticated is unauthorized

### ISSUE THREAD

**Issue by kamicut** [developmentseed/osm-teams#74]
When we visit a team page and are unauthenticated, the api and site show unauthorized errors. What should the behavior be @LanesGood? I think it should still show the team but prompt to log in?

**Comment by LanesGood** [comment]
@kamicut All information on a team page should be publicly viewable except for the member list. A prompt to log in is a good idea - we can also have any action buttons replaced/redirected to the sign up/login page
