### ISSUE TITLE
Adding users to private & unlisted teams

### ISSUE THREAD

**Issue by sethvincent** [developmentseed/osm-teams#82]
If a team has `privacy=private`, this requires a moderator to add/invite any new users.

We should decide how much information is shown to a user that does not belong to a team. 

Does the page for a private team 404 for someone that isn't logged in? This would be similar to how private repos work on github. Or should very basic information be shown?

**Comment by kamicut** [comment]
I think there are two notions here: "open" vs "closed" about the ability to join a team, and "public" vs "private" about certain information that is divulged, for example the list of members.

We can collapse the two for simplicity, but I think this is a question best answered by potential team moderators and how they want to manage teams. @LanesGood

**Comment by LanesGood** [comment]
We discussed three possible options for privacy: 
`public` = open, listed and fully viewable
`private` = closed by default, listed but with members hidden
`unlisted` = closed and unlisted, thus 404

`closed` is separate from private` We had discussed private teams being closed by default, but not unlisted. Moderators of `closed` team do need to add/invite any new users. A `closed` team should still be public by default.

**Comment by sethvincent** [comment]
Does "closed" mean that the team has `require_join_request=true`?

Because we don't have a column called `closed` or `privacy` option called `closed` it's very unclear what "closed" means. It's a little more verbose but it would be useful to specifically reference `require_join_request` instead of "closed" if that's what we're talking about.

So just to restate this to make sure I've got it right:

- `privacy=public && require_join_request=false`, all team info is publicly visible, anyone can join
- `privacy=public && require_join_request=true`, all team info is publicly visible, users must request to join or be added by moderator
- `privacy=private` implicitly this means `require_join_request=true`, members are hidden but other team info is publicly available, users must request to join or be added by moderator
- `privacy=unlisted` implicitly this means `require_join_request=true` (and users cannot even make join requests), 404s if requested by someone not in the team, users must  be added by moderator

**Comment by kamicut** [comment]
yes, closed in this context means `require_join_request=true`. The possibilities you list are correct, I think they are the only ones we need to implement.

**Comment by sethvincent** [comment]
OK, cool. Based on all this I think my original idea for this pr, moderators being able to add users manually, is not applicable because moderators already can add users manually.

Instead, we now have these issues:
- for a user that is not a member of a private team, only the team info & a request to join button should be displayed, not the team members #98
- finish implementing unlisted teams #96 
- users can request to join public or private teams that have `require_join_request=true` #81
- add users by username #97 

Closing this as the above issues are a better outline of the tasks.
